config/routes.rb
Budgeteer::Application.routes.draw do
  resources :commodities

  resources :vendors

  resources :categories

  resources :users
  resources :transactions do
    member do
      get 'clone'
    end
  end
  
  resources :sessions, only: [:new, :create, :destroy]
  match '/signup',  to: 'users#new'
  match '/signin',  to: 'sessions#new'
  match '/signout', to: 'sessions#destroy', via: :delete

  match '/help',    to: 'static_pages#help'
  match '/about',   to: 'static_pages#about'
  match '/contact', to: 'static_pages#contact'

  resources :accounts do
    resources :transactions
  end

  match 'categories/:id/transactions' => 'transactions#categorize'
  match 'categories/:id/merge' => 'transactions#merge_categories'
  match 'accounts/:id/reconcile' => 'transactions#reconcile'

  root :to => 'static_pages#home'

end

app/controllers/transactions_controller.rb
class TransactionsController < ApplicationController
  before_filter :signed_in_user
 
  # GET /transactions
  # GET /transactions.json
  def index
    @account = Account.find(params[:account_id])
    if (params[:page].nil?)
      page_num = 1;
    else
      page_num = Integer(params[:page])
    end
    if (Integer(page_num)>1)
      prior_transactions=@account.transactions.paginate(:page => 1, :per_page => 15*(page_num-1), :order => "date DESC")
      @page_balance = @account.final_balance - prior_transactions.to_a.sum {|transaction| transaction.amount}
    else
      @page_balance = @account.final_balance
    end
    @transactions = @account.transactions.search(params[:search]).paginate(:page => page_num, :per_page => 15, :order => "date DESC")

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @transactions }
    end
  end

  def categorize
    @month_transactions = Transaction.find_all_by_category_id(params[:id]).group_by { |d| d.date.beginning_of_month }
    @category = Category.find(params[:id])
    respond_to do |format|
      format.html #{ render categorize.html.erb }
      format.json { render json: @transactions }
    end
  end

  def reconcile
    @account = Account.find(params[:id])
    ##get the starting balance for the page
    # if (params[:page].nil?)
    #   page_num = 1;
    # else
    #   page_num = Integer(params[:page])
    # end
    # if (Integer(page_num)>1)
    #   prior_transactions=@account.transactions.paginate(:page => 1, :per_page => 15*(page_num-1), :order => "date DESC")
    #   @page_balance = @account.final_balance - prior_transactions.to_a.sum {|transaction| transaction.amount}
    # else
    #   @page_balance = @account.final_balance
    # end
    @transactions = @account.unreconciled

    respond_to do |format|
      format.html #{ render index.html.erb }
      format.json { render json: @transactions }
    end
  end

  # GET /transactions/1
  # GET /transactions/1.json
  def show
    #1st you retrieve the post thanks to params[:post_id]
    account = Account.find(params[:account_id])
    #2nd you build a new one
    @transaction = account.transactions.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @transaction }
    end
  end

  # GET /transactions/new
  # GET /transactions/new.json
  def new
    #1st you retrieve the post thanks to params[:post_id]
    account = Account.find(params[:account_id])
    #2nd you build a new one
    @transaction = account.transactions.build

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @transaction }
    end
  end

  # GET /transactions/1/edit
  def edit
    account = Account.find(params[:account_id])
    @transaction = account.transactions.find(params[:id])
  end

  # POST /transactions
  # POST /transactions.json
  def create
    account = Account.find(params[:account_id])
    @transaction = account.transactions.create(params[:transaction])

    respond_to do |format|
      if @transaction.save
        format.html { redirect_to account_transactions_path(account), notice: 'Transaction was successfully created.' }
        format.json { render json: @transaction, status: :created, location: [@transaction.account, @transaction] }
      else
        format.html { render action: "new" }
        format.json { render json: @transaction.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /transactions/1
  # PUT /transactions/1.json
  def update
    account = Account.find(params[:account_id])
    @transaction = account.transactions.find(params[:id])
    respond_to do |format|
      if @transaction.update_attributes(params[:transaction])
        format.html { redirect_to [@transaction.account, @transaction], notice: 'Transaction was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @transaction.errors, status: :unprocessable_entity }
      end
    end
  end

  def  clone
    @transaction = Transaction.find(params[:id]).dup
    @transaction.date = Date.today
    @transaction.is_cleared = false
    respond_to do |format|
      if @transaction.save
        format.html { redirect_to account_transactions_path(@transaction.account), notice: 'Transaction was successfully cloned.' }
        format.json { render json: @transaction, status: :created, location: [@transaction.account, @transaction] }
      else
        format.html { render action: "new" }
        format.json { render json: @transaction.errors, status: :unprocessable_entity }
      end    
    end
     
  end

  # DELETE /transactions/1
  # DELETE /transactions/1.json
  def destroy
    account = Account.find(params[:account_id])
    @transaction = account.transactions.find(params[:id])
    @transaction.destroy

    respond_to do |format|
      format.html { redirect_to account_transactions_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/transactions_helper.rb
module TransactionsHelper
	require 'open-uri'

	def getPrices()
		# { "Gold" => 2000, "Silver" => 22 }
		prices = Hash.new
		web_page = open("http://www.kitco.com/texten/texten.html")
		begin
		  while line = web_page.gets
		    md = /^\s*(Gold|Silver|Platinum|Palladium)\s*(\d*\.\d\d)\s*(\d*\.\d\d)\s*([+-].*[%])\s*(\d*\.\d\d)\s*(\d*\.\d\d)/.match(line)
		    if md
		      print "#{md[1]}: Bid (#{md[2]}), Ask (#{md[3]}), Low (#{md[5]}, High (#{md[6]}))\n"
		      mark = ("#{md[2]}".to_f+"#{md[3]}".to_f)/2
		      key = case "#{md[1]}"
		        when "Gold" then 2
		        when "Silver" then 1
		        when "Platinum" then 3
		        when "Palladium" then 4
		      end 
		      prices[key] = mark

		    else
		      # Do Nothing
		    end
		  end

		rescue Exception   
		  STDERR.puts "Failed to download from kitco"
		  raise
		end
		prices		
	end
end

app/views/transactions/_form.html.erb
<%= form_for([@transaction.account, @transaction]) do |f| %>
  <% if @transaction.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@transaction.errors.count, "error") %> prohibited this transaction from being saved:</h2>

      <ul>
      <% @transaction.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :date %><br />
    <%= f.date_select :date %>
  </div>
  <div class="field">
    <%= f.label :check %><br />
    <%= f.text_field :check %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_field :description %>
  </div>
  <div class="field">
    <%= f.label :amount %><br />
    <%= f.text_field :amount %>
  </div>
  <div class="field">
    <%= f.label :note %><br />
    <%= f.text_area :note %>
  </div>
  <div class="field">
    <%= f.label :is_cleared %><br />
    <%= f.check_box :is_cleared %>
  </div>
  <div class="field">
    <%= f.label :transfer_account_id %>
    <%= f.collection_select(:transfer_account_id, Account.without_account(@transaction.account), :id, :name) %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/transactions/_form_trans.html.erb
<%= form_for([@transaction.account, @transaction]) do |f| %>
  <% if @transaction.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@transaction.errors.count, "error") %> prohibited this transaction from being saved:</h2>

      <ul>
      <% @transaction.errors.full_messtx_directions.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :date %><br />
    <%= f.date_select :date %>
  </div>
  <div class="field">
    <%= f.label :check %><br />
    <%= f.text_field :check %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_field :description %>
  </div>
  <div class="field">
    <%= f.label :amount %><br />
    <%= f.text_field :amount %>
  </div>
  <div class="field">
    <%= f.label :note %><br />
    <%= f.text_area :note %>
  </div>
  <div class="field">
    <%= f.label :is_cleared %><br />
    <%= f.check_box :is_cleared %>
  </div>
  
  <div class="field">
    <%= f.label :transferAccount_id %>
    <%= f.collection_select(:transferAccount_id, Account.without_account(@transaction.account), :id, :name) %>
  </div>
  <%= f.hidden_field(:isTransfer) %>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/transactions/_show_form.html.erb
<p><b>Date:</b><%= best_in_place @transaction, :date, type: :date, :path => [@transaction.account, @transaction] %></p>
<p><b>Check:</b><%= best_in_place @transaction, :check, :path => [@transaction.account, @transaction] %></p>
<p><b>Description:</b><%= best_in_place @transaction, :description, :path => [@transaction.account, @transaction] %></p>
<p><b>Amount:</b><%= best_in_place @transaction, :amount, display_with: :number_to_currency, :path => [@transaction.account, @transaction] %></p>
<p><b>Category:</b><%= best_in_place @transaction, :category_id, :type => :select, :collection => Category::list_category_options, :path => [@transaction.account, @transaction] %></p>
<p><b>Note:</b><%= best_in_place @transaction, :note, :path => [@transaction.account, @transaction] %></p>
<p><b>Is cleared:</b><%= best_in_place @transaction, :is_cleared, type: :checkbox, :path => [@transaction.account, @transaction] %></p>

app/views/transactions/categorize.html.erb
<h2>Category: <%= @category.name %></h2>

<%= link_to '[Back]', categories_path %>
<P></P>
<div class="accordion" id="accordion2">
    <% @month_transactions.keys.sort.reverse.each do |month| %>
    <div class="accordion-group">
        <div class="accordion-heading">
            <a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion2" href="#<%=month.strftime("%B%Y") %>">
                <%= month.strftime("%B %Y") %>
                <% month_bal = 0.0 %>
                <% for transaction in @month_transactions[month] %>
                    <% month_bal += transaction.amount %>
                <% end %>
                <%= number_to_currency(month_bal) %>
            </a>
        </div>
        <div id="<%=month.strftime("%B%Y") %>" class="accordion-body collapse">
            <div class="accordion-inner">
                <table class="table table-striped table-bordered ">
                    <thead>
                      <tr>
                        <th>Account</th>
                        <th>Date</th>
                        <th>Desc</th>
                        <th>Amount</th>
                        <th>Category</th>
                        <th></th>
                      </tr>
                    </thead>
                    <tbody>
                        <% for transaction in @month_transactions[month] %>
                            <tr>
                                <td><%= transaction.account.name %></td>
                                <td><%= transaction.date %></td>
                                <td><%= transaction.description %></td>
                                <td><%= transaction.amount %></td>
                                <td><%= best_in_place transaction, :category_id, :type => :select, :collection => Category::list_category_options, :path => [transaction.account, transaction] %></td>
                            </tr>
                        <% end %>
                    </tbody>
                </table>
                
            </div>
        </div>
    </div>
    <BR>
    <% end %>
</div>

app/views/transactions/edit.html.erb
<h1>Edit transaction</h1>

<%= render 'form' %>

<%= link_to 'Back', account_transactions_path(@transaction.account) %>

app/views/transactions/index.html.erb
<h2><%= @account.name %></h2>
<%= link_to '[New Transaction]', new_account_transaction_path(@account) %> 
<%= link_away '[New Category]', new_category_path if !@account.isMetalType %>
<%= link_away '[New Commodity]', new_commodity_path if @account.isMetalType %>
<%= link_away '[New Vendor]', new_vendor_path if @account.isMetalType %>
<%= link_to '[Reconcile Account]', controller: "transactions", action: "reconcile", id: @account.id %> 
<%= link_to '[Back]', accounts_path %>
<br>
<br>
<% if @account.isMetalType == true %>
    <% prices = getPrices() %>
    <p><b>Total Value:</b><%= number_to_currency(value = @account.value(prices)) %></p>
    <p><b>Gain/Loss:</b><%= number_to_currency(value - @account.total_cost) %></p>
<% else %>
    <p><b>Available Balance:</b><%= number_to_currency(@account.reconciled_balance) %></p>
    <p><b>Balance:</b><%= number_to_currency(@account.final_balance) %></p>
<% end %>
<br>
<%= form_tag account_transactions_path(@account), :method => 'get' do %>
  <p>
    <%= text_field_tag :search, params[:search] %>
    <%= submit_tag "Search", :name => nil %>
  </p>
<% end %>
<% if @account.isMetalType == true %>
  
  <%= prices %>
<% end %>

<%= will_paginate %>

<div class='transactions'>
<table class="table table-striped table-bordered ">
    <thead>
      <tr>
        <% if @account.isMetalType == false %>
            <th>Is cleared</th>
            <th>Date</th>
            <th>Check</th>
            <th>Description</th>
            <th>Amount</th>
            <th>Category</th>
            <th>Balance</th>
            <th>Note</th>        
            <th></th>     
        <% else %>
            <th>Date</th>
            <th>Commodity</th>
            <th>Quantity</th>
            <th>Ounces Each</th>
            <th>Description</th>
            <th>Vendor</th>
            <th>Price/Oz</th>
            <th>Fee</th>
            <th>Cost</th>  
            <th>Current Value</th>
            <th>Profit/Loss</th>
            <th>Note</th>        
            <th></th>       
        <% end %>
        
      </tr>
    </thead>
    <tbody>
        <% balance = @page_balance %>
        <% @transactions.each do |transaction| %>
            
            <tr>
                <% if @account.isMetalType == false %>
                    <td><%= best_in_place transaction, :is_cleared, type: :checkbox, :path => [transaction.account, transaction] %></td>
                    <td><%= best_in_place transaction, :date, type: :date, :path => [transaction.account, transaction] %></td>
                    <td><%= best_in_place transaction, :check, :path => [transaction.account, transaction]  %></td>
                    <td><%= best_in_place transaction, :description, :path => [transaction.account, transaction] %></td>
                    <td><%= best_in_place transaction, :amount, display_with: :number_to_currency, :path => [transaction.account, transaction] %></td>
                    <td><%= best_in_place transaction, :category_id, :type => :select, :collection => Category::list_category_options, :path => [transaction.account, transaction] %></td>
                    <td><%= number_to_currency(balance) %></td>
                    <td><%= best_in_place transaction, :note, :path => [transaction.account, transaction] %></td>
                <% else %>    
                    <td><%= best_in_place transaction, :date, type: :date, :path => [transaction.account, transaction] %></td>
                    <td><%= best_in_place transaction, :commodity_id, :type => :select, :collection => Commodity::list_commodities, :path => [transaction.account, transaction] %></td>
                    <td><%= best_in_place transaction, :quantity, :path => [transaction.account, transaction]  %></td>
                    <td><%= best_in_place transaction, :ounces, :path => [transaction.account, transaction]  %></td>
                    <td><%= best_in_place transaction, :description, :path => [transaction.account, transaction] %></td>
                    <td><%= best_in_place transaction, :vendor_id, :type => :select, :collection => Vendor::list_vendors, :path => [transaction.account, transaction] %></td>
                    <td><%= best_in_place transaction, :amount, display_with: :number_to_currency, :path => [transaction.account, transaction] %></td>
                    <td><%= best_in_place transaction, :fee, display_with: :number_to_currency, :path => [transaction.account, transaction] %></td>
                    <% purchase = ((transaction.quantity * transaction.ounces * transaction.amount) + transaction.fee) %>
                    <td><%= number_to_currency(purchase) %></td>
                    <% current_val = transaction.quantity * transaction.ounces * prices[transaction.commodity_id] %>
                    <td><%= number_to_currency(current_val) %></td>
                    <td><%= number_to_currency(current_val - purchase) %></td>
                    <td><%= best_in_place transaction, :note, :path => [transaction.account, transaction] %></td>
                <% end %>           
                <td align="center">
                  <%= link_to raw("<i class=\"icon-pencil \"> </i>"), [transaction.account, transaction] %>
                  <%= link_to raw("<i class=\"icon-plus-sign \"> </i>"), :action => "clone", :id => transaction.id %>
                  <%= link_to raw("<i class=\"icon-trash \"> </i>"), [transaction.account, transaction], confirm: 'Are you sure?', method: :delete %>
                </td>
            </tr>
            <% balance -= transaction.amount %>
        <% end %>
    </tbody>
</table>
<%= will_paginate %>

app/views/transactions/new.html.erb
<h1>New transaction</h1>

<%= render 'form' %>

<%= link_to 'Back', account_transactions_path(@transaction.account) %>

app/views/transactions/new_transfer.html.erb
<h1>New Transfer</h1>

<%= render 'form' %>

<%= link_to 'Back', account_transactions_path(@transaction.account) %>

app/views/transactions/reconcile.html.erb
<h2>Reconciling: <%= @account.name %></h2>
<%= link_to '[New Transaction]', new_account_transaction_path(@account) %> 
<%= link_away '[New Category]', new_category_path %>
<%= link_to '[Done]', account_transactions_path(@account) %>

<p>
<%= number_to_currency(@account.reconciled_balance) %>
</p>

<div class='transactions'>
<table class="table table-striped table-bordered ">
    <thead>
      <tr>
        <th>Is cleared</th>
        <th>Date</th>
        <th>Check</th>
        <th>Description</th>
        <th>Amount</th>
        <th>Category</th>
        <th>Note</th>
        <th></th>
      </tr>
    </thead>
    <tbody>
        <% @transactions.each do |transaction| %>
            
            <tr>
                <td><%= best_in_place transaction, :is_cleared, type: :checkbox, :path => [transaction.account, transaction] %></td>
                <td><%= best_in_place transaction, :date, type: :date, :path => [transaction.account, transaction] %></td>
                <td><%= best_in_place transaction, :check, :path => [transaction.account, transaction] %></td>
                <td><%= best_in_place transaction, :description, :path => [transaction.account, transaction] %></td>
                <td><%= best_in_place transaction, :amount, display_with: :number_to_currency, :path => [transaction.account, transaction] %></td>
                <td><%= best_in_place transaction, :category_id, :type => :select, :collection => Category::list_category_options, :path => [transaction.account, transaction] %></td>
                <td><%= best_in_place transaction, :note, :path => [transaction.account, transaction] %></td>                
                <td align="center">
                  <%= link_to raw("<i class=\"icon-pencil \"> </i>"), [transaction.account, transaction] %>
                  <%= link_to raw("<i class=\"icon-plus-sign \"> </i>"), :action => "clone", :id => transaction.id %>
                  <%= link_to raw("<i class=\"icon-trash \"> </i>"), [transaction.account, transaction], confirm: 'Are you sure?', method: :delete %>
                </td>
            </tr>
            
        <% end %>
    </tbody>
</table>
<br />

app/views/transactions/show.html.erb
<p id="notice"><%= notice %></p>

<%= render 'show_form' %>

<%= link_to 'Back', account_transactions_path(@transaction.account) %>