config/routes.rb
Budgeteer::Application.routes.draw do
  resources :commodities

  resources :vendors

  resources :categories

  resources :users
  resources :transactions do
    member do
      get 'clone'
    end
  end
  
  resources :sessions, only: [:new, :create, :destroy]
  match '/signup',  to: 'users#new'
  match '/signin',  to: 'sessions#new'
  match '/signout', to: 'sessions#destroy', via: :delete

  match '/help',    to: 'static_pages#help'
  match '/about',   to: 'static_pages#about'
  match '/contact', to: 'static_pages#contact'

  resources :accounts do
    resources :transactions
  end

  match 'categories/:id/transactions' => 'transactions#categorize'
  match 'categories/:id/merge' => 'transactions#merge_categories'
  match 'accounts/:id/reconcile' => 'transactions#reconcile'

  root :to => 'static_pages#home'

end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    <b>Budgeteer</b>
    by Chris Gillanders
  </small>
  <nav>
    <ul>
      <li><%= link_to "About",   '#' %></li>
      <li><%= link_to "Contact", '#' %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container">
      <%= link_to "budgeteer", root_path, id: "logo" %>
      <nav>
        <ul class="nav pull-right">
          <li><%= link_to "Help", help_path %></li>
          <% if signed_in? %>
            
            <li id="fat-menu" class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                User <b class="caret"></b>
              </a>
              <ul class="dropdown-menu">
                <li><%= link_to "Accounts", accounts_path %></li>
                <li><%= link_to "Categories", categories_path %></li>
                <li><%= link_to "Settings", edit_user_path(current_user) %></li>
                <li class="divider"></li>
                <li>
                  <%= link_to "Sign out", signout_path, method: "delete" %>
                </li>
              </ul>
            </li>
          <% else %>
            <li><%= link_to "Sign in", signin_path %></li>
          <% end %>         
        </ul>
      </nav>
    </div>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= stylesheet_link_tag    "application", media: "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
    <%= render 'layouts/shim' %>    
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <%= yield %>
      <%= render 'layouts/footer' %>
     <br><br>
      <%= debug(params) if Rails.env.development? %>      
    </div>
  </body>
</html>