config/routes.rb
Budgeteer::Application.routes.draw do
  resources :commodities

  resources :vendors

  resources :categories

  resources :users
  resources :transactions do
    member do
      get 'clone'
    end
  end
  
  resources :sessions, only: [:new, :create, :destroy]
  match '/signup',  to: 'users#new'
  match '/signin',  to: 'sessions#new'
  match '/signout', to: 'sessions#destroy', via: :delete

  match '/help',    to: 'static_pages#help'
  match '/about',   to: 'static_pages#about'
  match '/contact', to: 'static_pages#contact'

  resources :accounts do
    resources :transactions
  end

  match 'categories/:id/transactions' => 'transactions#categorize'
  match 'categories/:id/merge' => 'transactions#merge_categories'
  match 'accounts/:id/reconcile' => 'transactions#reconcile'

  root :to => 'static_pages#home'

end

app/models/account.rb
# == Schema Information
#
# Table name: accounts
#
#  id               :integer          not null, primary key
#  name             :string(255)
#  description      :string(255)
#  created_at       :datetime         not null
#  updated_at       :datetime         not null
#  starting_balance :decimal(, )
#  web_address      :string(255)
#  user_name        :string(255)
#  password         :string(255)
#  note             :text
#  account_type     :integer          default(0)
#

class Account < ActiveRecord::Base
  require 'date'
  #has_secure_password
  validates :name, presence: true, uniqueness: true
  
  attr_accessible :description, :name, :starting_balance, :web_address, :user_name, :password, :note
  
  has_many :transactions, dependent: :destroy
  
  def final_balance
  	starting_balance + transactions.to_a.sum { |transaction| transaction.amount }
  end
 	
  def value(prices)
    transactions.to_a.sum { |transaction| transaction.quantity * transaction.ounces * prices[transaction.commodity_id] }
  end

  def total_cost()
    transactions.to_a.sum { |transaction| transaction.amount * transaction.quantity * transaction.ounces + transaction.fee  }
  end

  def available_balance
    starting_balance + transactions.to_a.sum { |transaction| transaction.date <= Date.today ? transaction.amount : 0 }
  end

  def reconciled_balance
    starting_balance + transactions.to_a.sum { |transaction| transaction.is_cleared? ? transaction.amount : 0 }
  end
  
  def isMetalType
    account_type == 1
  end
  # list of unreconciled transactions
  def unreconciled
    transactions.where("not is_cleared")
  end
  
  def self.reconciled_total
    accts = Account.all
    accts.to_a.sum { |m| m.reconciled_balance }
  end
  def self.final_total
    accts = Account.all
    accts.to_a.sum { |m| m.final_balance }
  end
end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
  before_filter :signed_in_user
 
  # GET /accounts
  # GET /accounts.json
  def index
    @accounts = Account.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @accounts }
    end
  end

  # GET /accounts/1
  # GET /accounts/1.json
  def show
    @account = Account.find(params[:id])
    
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @account }
    end
  end

  # GET /accounts/new
  # GET /accounts/new.json
  def new
    @account = Account.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @account }
    end
  end

  # GET /accounts/1/edit
  def edit
    @account = Account.find(params[:id])
  end

  # POST /accounts
  # POST /accounts.json
  def create
    @account = Account.new(params[:account])

    respond_to do |format|
      if @account.save
        format.html { redirect_to @account, notice: 'Account was successfully created.' }
        format.json { render json: @account, status: :created, location: @account }
      else
        format.html { render action: "new" }
        format.json { render json: @account.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /accounts/1
  # PUT /accounts/1.json
  def update
    @account = Account.find(params[:id])

    respond_to do |format|
      if @account.update_attributes(params[:account])
        format.html { redirect_to @account, notice: 'Account was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @account.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /accounts/1
  # DELETE /accounts/1.json
  def destroy
    @account = Account.find(params[:id])
    @account.destroy

    respond_to do |format|
      format.html { redirect_to accounts_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/accounts_helper.rb
module AccountsHelper
end

app/views/accounts/_account.html.erb
<div class="account_title"><%= account.name %></div>
<div class='transactions'>
<table class="table table-striped table-bordered ">
  <thead>
    <tr>
      <td>Num</td>
      <td>Date</td>
      <td>Chk #</td>
      <td>Payee</td>
      <td>Amount</td>
      <td>Category</td>
      <td>Note</td>
      <td>Balance</td>
    </tr>
    </thead>
    <tbody>
      <% balance = 0 %>
      <% i=0 %>
      <% @transactions.each do |transaction| %>
        <% balance += transaction.amount
           i += 1 %>
    	<tr>
    		<td><%= i %></td>
    		<td><%= transaction.date %></td>
    		<td><%= transaction.check %></td>
    		<td><%= transaction.description %></td>
    		<td><%= number_to_currency(transaction.amount) %></td>
    		<td><%= transaction.category %></td>
        <td><%= transaction.note %></td>
    		<td><%= number_to_currency(balance) %></td>
        <td align="center">
              <%= link_to 'Edit', edit_account_transaction_path(transaction.account, transaction) %>
              <%= link_to 'Destroy', [transaction.account, transaction], confirm: 'Are you sure?', method: :delete %></td>
    	</tr>
     <% end %>
 </tbody>  
</table>

</div>

app/views/accounts/_form.html.erb
<%= form_for(@account) do |f| %>
  <% if @account.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@account.errors.count, "error") %> prohibited this account from being saved:</h2>

      <ul>
      <% @account.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_field :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/accounts/edit.html.erb
<h1>Editing account</h1>

<%= render 'form' %>

<%= link_to 'Show', @account %> |
<%= link_to 'Back', accounts_path %>

app/views/accounts/index.html.erb
<% provide(:title, 'Accounts') %>
<div class="center hero-unit">
  <table class="table table-striped table-bordered" >
    <thead>
      <tr>
        <th>Name</th>
        <th>Description</th>
        <th>Reconciled Balance</th>
        <th>Final Balance</th>
        <th></th>
      </tr>
    </thead>

    
    <tbody>
      <% final_balance_total = 0.0 %>
      <% @accounts.each do |account| %>
        <tr>
          <td><%= best_in_place account, :name %></td>
          <td><%= best_in_place account, :description %></td>
          <% if account.isMetalType %>
            <td></td>
            <td><%= number_to_currency( value = account.value(getPrices())) %></td>
            <% final_balance_total += value %>
          <% else %>
            <td><%= number_to_currency(account.reconciled_balance) %></td>
            <td><%= number_to_currency(bal = account.final_balance) %></td>
            <% final_balance_total += bal %>
          <% end %>          
          <td align="center">
              <%= link_to raw("<i class=\"icon-play \"> </i>"), account_transactions_path(account) %>
              <%= link_to raw("<i class=\"icon-pencil \"> </i>"), account, :action => :show %>
              <%= link_to raw("<i class=\"icon-trash \"> </i>"), account, confirm: 'Are you sure?', method: :delete %>
          </td>
        </tr>
      <% end %>
      <tr>
        <td></td>
        <td align="right"><b>Total:</b></td>
        <td><%= number_to_currency(Account.reconciled_total) %></td>
        <td><%= number_to_currency(final_balance_total) %></td>
      </tr>
    </tbody>
  </table>
</div>
<br />

<%= link_to 'New Account', new_account_path %>

app/views/accounts/new.html.erb
<h1>New account</h1>

<%= render 'form' %>

<%= link_to 'Back', accounts_path %>

app/views/accounts/show.html.erb
<p>
	<b>Account: </b>
	<%= best_in_place @account, :name %>
</p>
<p>
	<b>Description: </b>
	<%= best_in_place @account, :description %>
</p>
<p>
	<b>Starting Balance: </b>
	<%= best_in_place @account, :starting_balance %>
</p>
<p>
	<b>Website URL: </b>
	<%= best_in_place @account, :web_address %>
</p>
<p>
	<b>User Name: </b>
	<%= best_in_place @account, :user_name %>
</p>
<p>
	<b>Password: </b>
	<%= best_in_place @account, :password %>
</p>
<p>
	<b>Notes: </b>
	<%= best_in_place @account, :note, type: :textarea %>
</p>

<%= link_to 'New Transaction', new_account_transaction_path(@account) %> 
<%= link_to 'Edit', edit_account_path(@account) %> 
<%= link_to 'Back', accounts_path %>